//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockhoodApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int inventoryID { get; set; }
        public string item_name { get; set; }
        public string cost { get; set; }
        public string description { get; set; }
        public string type { get; set; }
    }
}
