//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockhoodApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderSale()
        {
            this.WorkTasks = new HashSet<WorkTask>();
        }
    
        public int salesID { get; set; }
        public string qty { get; set; }
        public Nullable<System.DateTime> expectedDate { get; set; }
        public Nullable<int> customerID { get; set; }
    
        public virtual Cutomer Cutomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTask> WorkTasks { get; set; }
    }
}
