//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockhoodApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userID { get; set; }
        public Nullable<int> userRoleId { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string userDOB { get; set; }
        public string userAddress { get; set; }
        public Nullable<int> userDepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual RoleType RoleType { get; set; }
    }
}
